CREATE TABLE IF NOT EXISTS `Registration_Zany` (
  `id` int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `name` varchar(240) NOT NULL,
  `email` varchar(240) NOT NULL,
  `password` varchar(240) NOT NULL,
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `Status` (
  `stid` int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `id` int(11) NOT NULL,
  `msg` varchar(250) NOT NULL
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

CREATE TABLE IF NOT EXISTS `Friends`(
  `FrID` int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `id` int(11) NOT NULL,
  `Request_Status` varchar(20) NOT NULL
)ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;
